name: Build and deploy Python app to Azure Web App - RhinoPythonEmbedService

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install -r SocialMediaProject/EmbedService/requirements.txt

      - name: Upload Python service
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            SocialMediaProject/EmbedService/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D7800CA065164F7B8279B5AEBB30A351 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_917C8011286F477FBE37D5EE5B081D3F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6C9BFD17106B47BDB42466FAB5030B2B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'RhinoPythonEmbedService'
          slot-name: 'Production'
